server:
  port: 60000 #端口开的不常用端口段 降低被扫描概率
  servlet:
    context-path: /y-doc
spring:
  application:
    name: y-doc #元Doc
  datasource:
    url: jdbc:mysql://101.200.151.217:3306/y_doc?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: "ydoc"
    password: "!QAZ2wsx#EDC"  # 使用双引号排除类似yaml解析 !,#等特殊符号的问题
    driverClassName: com.mysql.cj.jdbc.Driver

minio:
  endpoint: http://101.200.151.217:9090  #MinIO服务所在地址
  bucketName: public #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
  bucket:
    img: img

ydoc:
  jwt:
    #管理端
    #jwt签名加密使用的密钥
    admin-secret-key: YDOC001022
    #过期时间
    admin-ttl: 7200000
    #前端传递的令牌名称
    admin-token-name: token
    #用户端
    #jwt签名加密使用的密钥
    user-secret-key: ydoctjy
    #过期时间
    user-ttl: 7200000
    #前端传递的令牌名称
    user-token-name: authentication

  #微信小程序appid以及密钥
  wechat:
    appid: wx78c4fef9b9f2f1ec
    secret: 048182268ad64ac9780dc194595b46e6


